"""Skill: Generate a structured analysis report from accumulated results."""
from __future__ import annotations

import glob
import json
import os
from pathlib import Path

from analysis.skills.base_skill import BaseSkill
from analysis.llm_client import query_llm


PET_REPORT_TEMPLATE = """
# PET/CT Quantitative Analysis Report

## 1. Patient & Study Information
| Field | Value |
|---|---|
| Patient Name | {patient_name} |
| Patient ID | {patient_id} |
| Study Date | {study_date} |
| Radiopharmaceutical | {tracer} |
| Injected Dose | {injected_dose} |
| Uptake Time | {uptake_time} |
| Scanner Model | {scanner} |
| Study Description | {study_description} |

## 2. Technical Parameters
| Parameter | Value |
|---|---|
| CT Series | {ct_series} |
| PET Series | {pet_series} |
| Slice Thickness (CT) | {ct_slice_thickness} |
| Reconstruction | {reconstruction} |
| Attenuation Correction | {attenuation_correction} |

## 3. Reference Organ SUV
| Organ | SUVmean | SUVmax | Volume (ml) |
|---|---|---|---|
{organ_suv_rows}

## 4. Lesion Analysis
### 4.1 Detection Summary
- Total lesions detected: {total_lesions}
- Detection method: {detection_method}

### 4.2 Lesion Details
| # | Location | SUVmax | SUVmean | Volume (ml) | Threshold | Notes |
|---|---|---|---|---|---|---|
{lesion_rows}

### 4.3 Aggregate Metrics
| Metric | Value |
|---|---|
| Total Metabolic Tumor Volume (MTV) | {total_mtv} ml |
| Total Lesion Glycolysis (TLG) | {total_tlg} g |
| Highest SUVmax | {highest_suvmax} |

## 5. Segmentation Summary
{segmentation_summary}

## 6. Visual Interpretation
{vision_interpretation}

## 7. Impression
{impression}

## 8. Recommendations
{recommendations}

---
*Report generated by DICOMclaw Quantitative Analysis Agent*
*Study UID: {study_uid}*
"""


class GenerateReportSkill(BaseSkill):
    name = "generate_report"
    description = (
        "Generate a structured markdown report summarising all analysis results "
        "(SUV stats, lesion quantification, segmentation, vision interpretation) for a study. "
        "Uses a standardized PET/CT report template."
    )
    input_modalities = []

    def run(self, studies_dir: str, results_dir: str, **kwargs) -> dict:
        study_uid = kwargs.get("study_uid", "")
        title = kwargs.get("title", "PET/CT Quantitative Analysis Report")

        if not study_uid:
            return {"status": "error", "message": "study_uid is required."}

        study_results = Path(results_dir) / study_uid
        if not study_results.exists():
            return {"status": "error", "message": f"No results found for study {study_uid}."}

        # Gather all available data
        context_parts: list[str] = []

        # CSV tables
        tables_dir = study_results / "tables"
        if tables_dir.exists():
            for csv_file in sorted(tables_dir.glob("*.csv")):
                content = csv_file.read_text()
                context_parts.append(f"### {csv_file.stem}\n```csv\n{content}\n```")

        # Existing reports / interpretations
        reports_dir = study_results / "reports"
        if reports_dir.exists():
            for md_file in sorted(reports_dir.glob("*.md")):
                if "final_report" in md_file.name:
                    continue  # Don't include previous final reports
                content = md_file.read_text()[:3000]
                context_parts.append(f"### {md_file.stem}\n{content}")

        # List available visualizations
        plots_dir = study_results / "plots"
        if plots_dir.exists():
            plot_files = sorted(plots_dir.rglob("*.png"))
            if plot_files:
                plot_list = "\n".join(
                    f"- {os.path.relpath(p, results_dir)}" for p in plot_files[:20]
                )
                context_parts.append(f"### Available Visualizations\n{plot_list}")

        # Segmentation files
        seg_dir = study_results / "segmentations"
        if seg_dir.exists():
            seg_files = sorted(seg_dir.glob("*"))
            if seg_files:
                seg_list = "\n".join(f"- {f.name}" for f in seg_files)
                context_parts.append(f"### Segmentation Files\n{seg_list}")

        if not context_parts:
            return {"status": "error", "message": "No analysis results found to compile into a report."}

        context_text = "\n\n".join(context_parts)

        # Generate report via LLM using the PET report template
        prompt = f"""Based on the following analysis results for a PET/CT study, generate a structured clinical report.

Use EXACTLY this template structure, filling in all fields from the available data.
If a field is not available, write "N/A" or "Not assessed".

## Report Template:
{PET_REPORT_TEMPLATE}

## Available Analysis Data:
{context_text}

## Instructions:
1. Fill in ALL template fields using the available data above.
2. For organ SUV rows, use the format: | Organ | SUVmean | SUVmax | Volume (ml) |
3. For lesion rows, use the format: | # | Location | SUVmax | SUVmean | Volume (ml) | Threshold | Notes |
4. Calculate aggregate metrics (MTV, TLG) from individual lesion data if available. TLG = SUVmean × Volume for each lesion, summed.
5. Write the Impression section as a concise clinical summary with key findings.
6. Write Recommendations based on the findings.
7. Use relative file paths for any image references (e.g., plots/mip/mip_000.png).
8. Write in professional medical language with specific quantitative values.
9. Study UID: {study_uid}

Generate the complete report now:"""

        print("Generating report via LLM...")
        response = query_llm(
            [{"role": "user", "content": prompt}],
            temperature=0.2,
            max_tokens=4096,
        )

        if response.startswith("API Error") or response.startswith("Error:"):
            return {"status": "error", "message": response}

        # Save report
        reports_dir_path = study_results / "reports"
        reports_dir_path.mkdir(parents=True, exist_ok=True)
        report_path = reports_dir_path / "final_report.md"
        report_path.write_text(response)

        return {
            "status": "ok",
            "message": f"Report generated: {os.path.relpath(str(report_path), results_dir)}",
            "report": os.path.relpath(str(report_path), results_dir),
            "report_content": response[:1000],
        }
